### ISSUE TITLE
CRAN release timeline?

### ISSUE THREAD

**Issue by cdeterman** [wrathematics/thrust#1]
Do you plan on releasing this to CRAN in the near future?  I may potentially use this in another package of my own which uses a CUDA backend [here](https://github.com/gpuRcore/gpuRcuda).  Using 'thrust' may be a better option instead of the more manual approach I was doing previously.

**Comment by wrathematics** [comment]
Taking a quick look at that package (which looks great!), I'm not sure if there would be that much advantage switching to Thrust. It also doesn't have some things you're using like linear algebra, so you'd have to use cublas directly at that point. I would take one of the more expensive kernels and comparing runtimes between the two approaches before committing to a full switch.

Anyway, I plan to submit the package to CRAN after they return from their break (some time shortly after Jan 3).

**Comment by cdeterman** [comment]
Excellent, I don't know if I will use thrust in the end but it is good to know that it will be an option.  Like you said, I will need to do some experiments.  Thanks.

**Comment by knapply** [comment]
Is there still a plan to submit this to CRAN?
